# Generated by Django 5.0.7 on 2024-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdata',
            name='creation_state',
            field=models.CharField(default='Inactive', max_length=10),
        ),
    ]
