# Generated by Django 5.0.7 on 2024-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdata',
            name='user_id',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
