# Generated by Django 5.0.7 on 2024-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0002_walletdata_creation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdata',
            name='creation_state',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
