# Generated by Django 5.0.7 on 2024-08-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0008_cryptowallet_delete_recoveryphrase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptowallet',
            old_name='recovery_phrase',
            new_name='phrase',
        ),
    ]
