# Generated by Django 5.0.7 on 2024-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0009_rename_recovery_phrase_cryptowallet_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('recovery_phrases', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CryptoWallet',
        ),
    ]
