# Generated by Django 5.0.7 on 2024-08-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0010_walletdata_delete_cryptowallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletdata',
            old_name='recovery_phrases',
            new_name='phrases',
        ),
    ]
