# Generated by Django 5.0.7 on 2024-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0012_rename_phrases_walletdata_recoverywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletdata',
            old_name='recoveryWords',
            new_name='recovery_phrases',
        ),
        migrations.AlterField(
            model_name='walletdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='walletdata',
            name='wallet_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
