# Generated by Django 5.0.7 on 2024-08-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletPassword',
        ),
        migrations.RenameField(
            model_name='walletpassword',
            old_name='wallet_password',
            new_name='password',
        ),
    ]
