# Generated by Django 5.0.7 on 2024-08-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0002_rename_wallet_walletpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletpassword',
            old_name='password',
            new_name='wallet_password',
        ),
    ]
