# Generated by Django 5.0.7 on 2024-08-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletmanagement', '0005_recoveryphrase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoveryPhrase',
        ),
    ]
